apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: airbyte
  namespace: default
spec:
  interval: 10m0s
  dependsOn:
    - name: airbyte
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: ./apps/data-prod
  prune: true
  wait: true
  timeout: 5m0s
