apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/data-prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
