apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: airbyte
  namespace: airbyte
spec:
  interval: 5m
  targetNamespace: airbyte
  chart:
    spec:
      chart: airbyte
      version: '0.54.157' # App Version 0.52.0
      sourceRef:
        kind: HelmRepository
        name: airbyte
        namespace: airbyte
      interval: 1m
  values:
    global:
      jobs:
        kube:
          images:
            busybox: busybox:1.35
            curl: curlimages/curl:7.83.1
            socat: alpine/socat:1.7.4.3-r0

    worker:
      resources:
        requests:
          cpu: 100m
          memory: 2500Mi
        limits:
          cpu: 2048m
          memory: 40960Mi
      containerOrchestrator:
        image: airbyte/container-orchestrator:0.52.0
    workload-launcher:
      containerOrchestrator:
        image: airbyte/container-orchestrator:0.52.0
